// AUTO-GENERATED by demo/build-audio.sh — voiceover + music timings in seconds. Do not edit by hand.
export const audio = {
  vo: "vo.mp3",
  music: "music.mp3",
  introSeconds: 11.477959,
  bodySeconds: 53.414331,
  outroSeconds: 8.295420,
  totalSeconds: 73.187710,
};
