#!/usr/bin/env bash
# Generates the Sphinx demo voiceover (macOS `say`) + a subtle ambient music bed, and writes a
# duration manifest that the Remotion composition reads to sync visuals to the narration.
#
# Swap the voice:  VOICE="Daniel" ./build-audio.sh    (Daniel = en_GB, Samantha = en_US)
# Swap to a premium VO: replace remotion/public/vo.mp3 with your ElevenLabs / recorded file,
#   then keep the durations roughly in sync (or re-measure).
set -euo pipefail
cd "$(dirname "$0")"

VOICE="${VOICE:-Samantha}"
RATE="${RATE:-176}"
PUB="remotion/public"
TMP="$(mktemp -d)"
mkdir -p "$PUB"

INTRO="Remote tech support is fast. But the fix is rarely written down, and the knowledge evaporates after every ticket. Team Sphinx built an A.I. copilot that solves the incident, and documents itself."

BODY="It pulls your assigned tickets straight from the Phoenix E.R.P., loads the customer's system, and connects over S.S.H., entirely under your control. \
Watch it work. The agent runs read-only diagnostics automatically, checking services, logs, and ports, and streams every step into a live trace. No black box: you see exactly what it inspects, and why. \
The moment it wants to change the system, it stops. Every write is gated. You approve, edit, or reject. Here, it has found the root cause, and proposes a minimal, lasting fix. One click, and it runs over S.S.H. \
It validates the result: the service is healthy, and the fix survives a reboot. The customer's problem is genuinely solved, not just patched. \
Then it writes the documentation for you. Root cause, the exact commands, and proof that it works, straight back into the E.R.P."

OUTRO="Deterministic safety. Secrets never reach the model. Every action, logged. Sphinx. The technician that never forgets to write it down."

gen () { say -v "$VOICE" -r "$RATE" -o "$TMP/$2.aiff" "$1"; ffmpeg -y -i "$TMP/$2.aiff" -ar 44100 -ac 2 "$TMP/$2.wav" >/dev/null 2>&1; }
dur () { ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$1"; }

gen "$INTRO" intro
gen "$BODY"  body
gen "$OUTRO" outro

DI=$(dur "$TMP/intro.wav"); DB=$(dur "$TMP/body.wav"); DO=$(dur "$TMP/outro.wav")

ffmpeg -y -i "$TMP/intro.wav" -i "$TMP/body.wav" -i "$TMP/outro.wav" \
  -filter_complex "[0][1][2]concat=n=3:v=0:a=1" "$PUB/vo.mp3" >/dev/null 2>&1
TOTAL=$(dur "$PUB/vo.mp3")

# Subtle ambient bed (C3–G3–C4 drone, soft tremolo + lowpass + light reverb), well under the VO.
ffmpeg -y \
  -f lavfi -i "sine=frequency=130.81:duration=$TOTAL" \
  -f lavfi -i "sine=frequency=196.00:duration=$TOTAL" \
  -f lavfi -i "sine=frequency=261.63:duration=$TOTAL" \
  -filter_complex "[0][1][2]amix=inputs=3,tremolo=f=0.12:d=0.5,lowpass=f=900,aecho=0.8:0.5:70:0.35,volume=0.15" \
  -ar 44100 "$PUB/music.mp3" >/dev/null 2>&1

cat > remotion/src/audio-manifest.ts <<EOF
// AUTO-GENERATED by demo/build-audio.sh — voiceover + music timings in seconds. Do not edit by hand.
export const audio = {
  vo: "vo.mp3",
  music: "music.mp3",
  introSeconds: ${DI},
  bodySeconds: ${DB},
  outroSeconds: ${DO},
  totalSeconds: ${TOTAL},
};
EOF

echo "voice=$VOICE  intro=${DI}s  body=${DB}s  outro=${DO}s  total=${TOTAL}s"
echo "wrote $PUB/vo.mp3, $PUB/music.mp3, remotion/src/audio-manifest.ts"
